
name: basicTest

on: 
  [repository_dispatch]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: Print Folders 
          ls
      
      - name: Restore Nuget Packages
        run: nuget restore DevOpsAutomatedUITest\CreditCards.UITests\CreditCards.UITests.csproj
        
      - name: Build the solution
        run: msbuild DevOpsAutomatedUITest\CreditCards.UITests\CreditCards.UITests.csproj
     
      - name: Test
        run: dotnet test --no-build --verbosity normal
      
